### ISSUE TITLE
Do not reinstall dependencies in the restore script

### ISSUE THREAD

**Issue by ketsapiwiq** [YunoHost-Apps/uptime-kuma_ynh#101]
Get rid of this and test: 
https://github.com/YunoHost-Apps/uptime-kuma_ynh/blob/27a580f669472e1e63a8001c02374d42f7977d97/scripts/restore#L29

**Comment by orhtej2** [comment]
What if you're restoring on clean system?

**Comment by ketsapiwiq** [comment]
Yes I didn't think properly, you're right!
