### ISSUE TITLE
Invalid array

### ISSUE THREAD

**Issue by sthaydn** [YunoHost-Apps/uptime-kuma_ynh#20]
Hi there,

when I want to create status pages, I always get an "invalid array" when saving. I am on the latest Yunohost and Uptime Kuma, the monitors are created ok.

Regards,

Stefan

**Comment by ketsapiwiq** [comment]
This is weird ,it's supposed to be fixed by 1.14.1 according to this. https://github.com/louislam/uptime-kuma/issues/1537
Can you provide more screenshots or console logs please, eventually? It may be about the app itself. Thanks

**Comment by ketsapiwiq** [comment]
You can first try:
```bash
cd /var/www/uptime-kuma/ && npm run download-dist
```

**Comment by sthaydn** [comment]
Yes, that command above did the trick. The status pages could now be created. Thank you very much!

**Comment by Tagadda** [comment]
I have the same issue after upgrading to `master` branch.
`npm run download-dist` did fix the issue.

**Comment by ketsapiwiq** [comment]
Hi @Tagadda I'm closing this until someone has this problem on a fresh install :)
