### ISSUE TITLE
uptime-kuma don't load admin page content

### ISSUE THREAD

**Issue by Christophe31** [YunoHost-Apps/uptime-kuma_ynh#27]
Edit:
<img width="276" alt="image" src="https://user-images.githubusercontent.com/84683/175228315-0565d7ac-41c3-4371-ba25-9530dbf99ae9.png">

When I load my admin page since last update I can't load any content or options.

### Describe the bug

Since last upgrade, most of static css/js related files are 404ed. most of the admin interface don't works anymore.

Note, I already tryed ```npm run download-dist``` in ```/var/www/uptime-kuma/```

<img width="99" alt="image" src="https://user-images.githubusercontent.com/84683/175226860-b886d113-c681-4c1a-a9cc-22953e5196ab.png">

**Comment by ketsapiwiq** [comment]
Hi!
Do you mean last update 1.16.1 or another one like 1.16.0?
I have not had this so I'd need more info. 
Can you try `yunohost app upgrade uptime-kuma -u https://github.com/YunoHost-Apps/uptime-kuma_ynh/tree/maser --debug` and give us the output?
Thanks!

**Comment by Christophe31** [comment]
```
root@intra:~# yunohost app upgrade uptime-kuma -u https://github.com/YunoHost-Apps/uptime-kuma_ynh/tree/maser --debug
84   DEBUG initializing base actions map parser for cli
84   DEBUG loading actions map
85   DEBUG building parser...
94   DEBUG building parser took 0.009s
95   DEBUG acquiring lock...
103  DEBUG lock has been acquired
110  DEBUG loading python module yunohost.app took 0.007s
110  DEBUG processing action [570269.1]: yunohost.app.upgrade with args={'app': ['uptime-kuma'], 'url': 'https://github.com/YunoHost-Apps/uptime-kuma_ynh/tree/maser', 'file': None, 'force': False, 'no_safety_backup': False}
112  INFO Now upgrading uptime-kuma...
147  DEBUG initializing ldap interface
167  DEBUG Hydrating config with current values
175  DEBUG Downloading...
5585 DEBUG action [570269.1] executed in 5.475s
5586 DEBUG lock has been released
5586 ERROR Could not fetch sources files, is the URL correct?
```
Thanks to you.

**Comment by ketsapiwiq** [comment]
I am sorry I made a typo in my previous command (`maser`).
Anyway, this can be used:
`yunohost app upgrade uptime-kuma -u https://github.com/YunoHost-Apps/uptime-kuma_ynh/tree/master --debug`

**Comment by Christophe31** [comment]
Damned, I didn't saw this typo, even if I took a second look at the url after the error message.
this upgrade had nothing above info (except one warning about dpkg version name formating which contained a v and not only numbers).

Maybe firefox js console logs can help to understand what's wrong, it looks like the connection to web-socket is wrong… the sed on the nginx files had no issues…

<img width="736" alt="image" src="https://user-images.githubusercontent.com/84683/175541570-19df1472-2458-4e73-8d3b-edc26e1ec227.png">

**Comment by ketsapiwiq** [comment]
It seems any asset on thé page doesn't load due to browser content security policy.
It may have to do with niginx config or HTTPS but I'm a bit l'ost about troubleshooting those. I'd suggest a second installation on a new domain maybe ?

**Comment by Christophe31** [comment]
I didn't do a thing and it works again, maybe some content policies have cache duration or I don't know what… but it look like time (~3/4 days) solved this issue.

You may close the issue as nobody seems affected anymore unless you want to keep it for further reference, thanx for your help.

**Comment by ketsapiwiq** [comment]
Great! :)
