### ISSUE TITLE
Github action for upstream releases is disabled

### ISSUE THREAD

**Issue by hidrarga** [YunoHost-Apps/uptime-kuma_ynh#31]
I noticed that the github action that checks for upstream releases is disabled due to inactivity : https://github.com/YunoHost-Apps/uptime-kuma_ynh/actions/workflows/updater.yml

![image](https://user-images.githubusercontent.com/2971096/192225141-52eda24d-27cb-44df-9ae0-6e673b19502f.png)

**Comment by ketsapiwiq** [comment]
Thanks, restarted it!
