### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by MacMatt** [YunoHost-Apps/uptime-kuma_ynh#50]
Hello

Any chance to see this package update any time ? :-) 
https://github.com/louislam/uptime-kuma/releases

Or you can explain how to update the package it not too cimpicated (really newbie here...)

Thanks for the work !

Matthieu

**Comment by ketsapiwiq** [comment]
Hi!
Haven't had the time to test it but there's the testing branch with version **1.19.6**: https://github.com/YunoHost-Apps/uptime-kuma_ynh/issues/50

The CI seems to have noticed some problems so any feedback you have on real problems would be welcome!
To install latest version from the testing branch you can do:
`yunohost app upgrade uptime-kuma -u https://github.com/YunoHost-Apps/uptime-kuma_ynh/tree/testing --debug`

**Comment by MacMatt** [comment]
Hello !

Thanks for the testing link
Update done with with no warning or mails in the log.

So far so good !

Matthieu

**Comment by ketsapiwiq** [comment]
Thanks for the test!
