### ISSUE TITLE
SMTP notification test fails. "Lost connection to the socket server"

### ISSUE THREAD

**Issue by kingannoy** [YunoHost-Apps/uptime-kuma_ynh#6]
### Describe the bug

When configuring SMTP notification all goes well until I want to perform a test of the connection. Then it give one or more socket connection errors.

I first tried reporting to the maintainer of the app here:
https://github.com/louislam/uptime-kuma/issues/1304

### Context

- Hardware: VPS online
- YunoHost version: 4.3.5
- I have access to my server: Through SSH and through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
  - If yes, please explain: but it has been around for a while, and there are different apps installed on there.
- Using, or trying to install package version/branch: uptime-kuma 1.11.3~ynh1

### Steps to reproduce

- Install Uptime Kuma via Yunohost
- Create a notification based on SMTP
- Test the notification

### Expected behavior

When doing this on the [demo server](http://demo.uptime.kuma.pet/) uptime kuma offers, I get a notification that the email has been sent. And the email is sent.

Initially I still had a email configuration issue on the side of the email server. In that case I got a *different* error in the demo server, giving me a hint as to what was going wrong.

### Actual behaviour

Instead of that the following text showing in a red bar:
```
Lost connection to the socket server. Reconnecting...
```
Sometimes (about one in three times) it will also show this after the first one:
```
Cannot connect to the socket server. [Error: websocket error] Reconnecting...
```
The notification modal will not progress after this, showing a infinite spinning "save" button:
![image](https://user-images.githubusercontent.com/36500946/153963383-5c4bd465-0629-48ef-b04f-0c2620ea5abe.png)

It's possible to close the modal with the :x: at the right top, but when you reopen it, it's still spinning. 

Refreshing the page let's you try again.

### Logs

Looking in the browser console I see:
```
Content Security Policy: This site (https://up.example.com) has a Report-Only policy without a report URI. CSP will not block and cannot report violations of this policy. 2
Content Security Policy: The page’s settings observed the loading of a resource at wss://up.example.com/socket.io/?EIO=4&transport=websocket (“default-src”). A CSP report is being sent. vendor.f2e417fe.js:55:57144
```
These are the logs I found in /var/log/uptime-kuma/uptime-kuma.log

```
os.js:68
      throw new ERR_SYSTEM_ERROR(ctx);
      ^

SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_interface_addresses returned Unknown system error 97 (Unknown system error 97)
    at Object.networkInterfaces (os.js:259:16)
    at resolver (/var/www/uptime-kuma/node_modules/nodemailer/lib/shared/index.js:16:34)
    at Object.module.exports.resolveHostname (/var/www/uptime-kuma/node_modules/nodemailer/lib/shared/index.js:74:5)
    at SMTPConnection.connect (/var/www/uptime-kuma/node_modules/nodemailer/lib/smtp-connection/index.js:326:27)
    at /var/www/uptime-kuma/node_modules/nodemailer/lib/smtp-transport/index.js:263:24
    at Immediate._onImmediate (/var/www/uptime-kuma/node_modules/nodemailer/lib/smtp-transport/index.js:70:35)
    at processImmediate (internal/timers.js:464:21) {
  code: 'ERR_SYSTEM_ERROR',
  info: {
    errno: 97,
    code: 'Unknown system error 97',
    message: 'Unknown system error 97',
    syscall: 'uv_interface_addresses'
  },
  errno: [Getter/Setter],
  syscall: [Getter/Setter]
}
```

This just in: According to the Uptime Kuma maintainer it may be similar/related to this issue:
https://forum.yunohost.org/t/ghost-4-20-3-ynh1-broke-all-editing-fixed/17629

I don't have any time left for this right now, but as soon as I can I will see if I can find this "security setting in the service configuration file" and see if commenting that out solves the problem.

**Comment by ketsapiwiq** [comment]
Thanks for the issue! 
I'm on my phone right now but this might be the culprit: https://github.com/YunoHost-Apps/uptime-kuma_ynh/blob/master/conf/systemd.service#L22

**Comment by ketsapiwiq** [comment]
Created the PR but haven't had time to test it personnally yet. https://github.com/YunoHost-Apps/uptime-kuma_ynh/pull/7

**Comment by kingannoy** [comment]
I commented out the line, but I don't see a improvement yet. 

Do I have to reload the configuration in some way? I did reboot the Yunohost server in the hope of this change fixing the problem...

This is where I made the change, this is the right file I think?

```
root@yunohost:/# cat /etc/yunohost/apps/uptime-kuma/conf/systemd.service | grep AF_UNIX
# RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6
```

**Comment by ketsapiwiq** [comment]
Yes but you need to do a
`systemctl daemon-reload` and then restarting the service or rebooting. This is necessary when editing a service file.

**Comment by kingannoy** [comment]
I'm sorry, I'm not experienced in this...

I did:
`root@yunohost:/home/admin# systemctl daemon-reload`

And rebooted yunohost from the webadmin. Should that be enough?

The problem is still there for me.

**Comment by ketsapiwiq** [comment]
Yes it should be enough, so it means this requires more investigation!
I remember very quickly trying the SMTP alerting and having the service crash, this may be the same error. It was before this `RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6 for SMTP` got added.
Maybe it still fails with a different error in logs? I'll try to check this week-end.

**Comment by kingannoy** [comment]
> Maybe it still fails with a different error in logs? I'll try to check this week-end.

I just tried again and I get the exact same error as the one I shared in the first post here.

If I have time I will see if I can spin up a new server, install Yunohost, install uptime kuma, to see if it also happens in a fresh install.

**Comment by ketsapiwiq** [comment]
And if the update doesn't appear in the possible app updates, you can still do:
`sudo yunohost app upgrade uptime-kuma -u https://github.com/YunoHost-Apps/uptime-kuma_ynh/tree/master --debug`

The correct version is `1.11.3~ynh2`.

**Comment by kingannoy** [comment]
YEEEEES! IT WORKS!

Epic! :smile: Thanks for the quick fix!

I did not revert the change I made to the "package", the upgrade showed up under System update and I ran it from there.

**Comment by ketsapiwiq** [comment]
Perfect! Thanks for the feedback 😊

**Comment by chjohn22** [comment]
@ketsapiwiq I've got a similar problem with Matrix notifications. When testing the server the error: "Error: Error: socket hang up!" appears.
