### ISSUE TITLE
Ping test fails

### ISSUE THREAD

**Issue by Tagadda** [YunoHost-Apps/uptime-kuma_ynh#8]
### Describe the bug

Every Ping test fails with an "EPERM" errors.

`Monitor #14 'test': Failing: spawn EPERM | Interval: 60 seconds | Type: ping`

### Context

- Hardware: VPS bought online
- YunoHost version: 4.3.6.3
- I have access to my server: Through SSH and through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: yes
  - If yes, please explain: ipv6 only
- Using, or trying to install package version/branch: master

### Steps to reproduce

- Install the uptime-kuma on a fresh YunoHost
- Create a new Ping Monitor
- The monitor is "Failing: spawn EPERM"

### Expected behavior

The Ping Monitor should work.

**Comment by ketsapiwiq** [comment]
Did it work? :) feel free to reopen
